import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css'
import Menu from '../components/Menu'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>CursosCast</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu></Menu>
        <h1 className={styles.title}>
          Bem Vindo a CursosCast!
        </h1>

    </div>
  )
}
